using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class CMUSurgeryWindow : FancyWindow
{
    public CMUSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
