using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Medical.Scanner;

[GenerateTypedNameReferences]
public sealed partial class HealthScannerWindow : DefaultWindow
{
    private static readonly TimeSpan ServerLoadingPulse = TimeSpan.FromSeconds(0.4);

    [Dependency] private readonly IGameTiming _timing = default!;

    private TimeSpan _loadingStart;
    private TimeSpan _loadingEnd;

    public HealthScannerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void ShowServerLoadingPulse()
    {
        _loadingStart = _timing.CurTime;
        _loadingEnd = _loadingStart + ServerLoadingPulse;
        LoadingPanel.Visible = true;
        LoadingSpinner.Visible = true;
        LoadingSpinner.Progress = 1f;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!LoadingPanel.Visible)
            return;

        LoadingSpinner.FromTime(_loadingStart, _loadingEnd);

        if (_timing.CurTime >= _loadingEnd)
            LoadingPanel.Visible = false;
    }
}
